# Generated by Django 5.1.6 on 2025-05-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
