# Generated by Django 5.1.6 on 2025-05-22 14:35

import apps.user.services.model_services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.user.services.model_services.validate_phone_number, django.core.validators.MinLengthValidator(11)], verbose_name='phone number'),
        ),
    ]
