# Generated by Django 5.1.5 on 2025-02-02 14:28

import apps.user.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profileuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[apps.user.services.validated_phone_number]),
        ),
    ]
